### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by pmalek-sumo**
**Description:** Update `main` with commits from https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/70d830354ccf8b03c72c651748ef84ec9d0008e9

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
Would that make sense to squash our commits?

**Comment by sumo-drosiek** [comment]
Is merge approach valid for maintaining forked repo?

**Comment by pmm-sumo** [comment]
I think I might have missed that PR and I guess it is no longer relevant as I rebased main already with upstream changes from 0.21.0.  BTW, due to our custom extensions to filter processor in core, we need to maintain and update our custom fork there as well (at least as of now)

**Comment by pmm-sumo** [comment]
> Would that make sense to squash our commits?

I think we should avoid making too many commits at once (especially affecting things that change during releases, like go.mod's, etc.) but otherwise we've been good as long as the changes were rebased rather than merged. I am thinking about several alternatives to make life easier:
* keeping an up-to-date branch with upstream changes
* using a totally different approach and instead of having a fork, start a new project that just takes dependencies from the core and contrib (similarly as [AWS does](https://github.com/aws-observability/aws-otel-collector)) - I find this the cleanest solution
* ...

What do you think @pmalek-sumo @sumo-drosiek @perk-sumo @pmatyjasek-sumo @dmolenda-sumo  ?

**Comment by pmalek-sumo** [comment]
> ... and I guess it is no longer relevant

Yup

> BTW, due to our custom extensions to filter processor in core, we need to maintain and update **our custom fork there** as well (at least as of now)

Where's that exactly :) ?

**Comment by sumo-drosiek** [comment]
@pmm-sumo Fresh project with otc contrib as dependency seems to fit the golang world and should be much easier to maintain, unless we have to change something in internal structures :sweat_smile:

**Comment by pmalek-sumo** [comment]
> > Would that make sense to squash our commits?
> 
> I think we should avoid making too many commits at once (especially affecting things that change during releases, like go.mod's, etc.) but otherwise we've been good as long as the changes were rebased rather than merged. I am thinking about several alternatives to make life easier:
> 
> * keeping an up-to-date branch with upstream changes
> * using a totally different approach and instead of having a fork, start a new project that just takes dependencies from the core and contrib (similarly as [AWS does](https://github.com/aws-observability/aws-otel-collector)) - I find this the cleanest solution
> * ...

I believe that issuing PRs straight from upstream's `main` branch makes most sense.
This is trivial with Github's UI, you can see the merge commit and inspect what came from upstream and what is our own work.
Rebasing is nice but IMHO not for a long running project like this one where with each "update from upstream" the rebase is more complicated and takes longer and longer.

The only concern with merge strat is that finding commits **only** on our fork (i.e. not upstreamable) might be slightly more difficult (but does it matter?)

**Comment by pmalek-sumo** [comment]
But maybe it's just me not being acquainted with https://github.com/aws-observability/aws-otel-collector

**Comment by pmm-sumo** [comment]
> > BTW, due to our custom extensions to filter processor in core, we need to maintain and update **our custom fork there** as well (at least as of now)
> 
> Where's that exactly :) ?

This thing: https://github.com/SumoLogic/opentelemetry-collector - we have two small changes there

**Comment by pmm-sumo** [comment]
> I believe that issuing PRs straight from upstream's `main` branch makes most sense.
> This is trivial with Github's UI, you can see the merge commit and inspect what came from upstream and what is our own work.
> Rebasing is nice but IMHO not for a long running project like this one where with each "update from upstream" the rebase is more complicated and takes longer and longer.
> 
> The only concern with merge strat is that finding commits **only** on our fork (i.e. not upstreamable) might be slightly more difficult (but does it matter?)

I think I fail to understand how that would suppose to work. In general we have two "lines" - the vanilla one (`opentelemetry/main`) and our distro (`SumoLogic/main`). Every now and then changes happen on each one of them. Our experience so far was following:

* when new OpenTelemetry Collector gets released, we rebase `SumoLogic/main` with changes from the recent release (so not strictly `main` but e.g. `releases/v0.21.x`), then apply any necessary changes and release it as e.g. `v0.21.0-sumo`
* when changes on our side happen, we merge it to `SumoLogic/main` and release it as a new minor version (e.g. `v0.21.1-sumo`)

Now, this is not perfect, but it seems it was working just fine. I would love to improve it and I think modularization (i.e. something akin to `aws-otel-collector`) would be ideal solution (maybe the only caveat being that changes to existing modules would need to be duplicated)

**Comment by pmalek-sumo** [comment]
> > I believe that issuing PRs straight from upstream's `main` branch makes most sense.
> > This is trivial with Github's UI, you can see the merge commit and inspect what came from upstream and what is our own work.
> 
> I think I fail to understand how that would suppose to work. In general we have two "lines" - the vanilla one (`opentelemetry/main`) and our distro (`SumoLogic/main`). Every now and then changes happen on each one of them. Our experience so far was following:

Whenever one wants to take in the changes from upstream the following PR would need to be created: https://github.com/SumoLogic/opentelemetry-collector-contrib/compare/main...open-telemetry:main ( if conflicts arise then merge locally from upstream to `branchX`, resolve conflicts, then issue PR with this branch)

And that's it.

If linux can work with this model https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/  (with 1 upstream to pull from) I think we could to.

But as I said 

> The only concern with merge strat is that finding commits **only** on our fork (i.e. not upstreamable) might be slightly more difficult (but does it matter?)

I'll have to take a look at the AWS otel model though.

**Comment by pmatyjasek-sumo** [comment]
> @pmm-sumo Fresh project with otc contrib as dependency seems to fit the golang world and should be much easier to maintain, unless we have to change something in internal structures 😅

I agree, it seems to be a good solution and much easier to maintain upstream changes

**Pull request closed without merging**
